# Generated by Django 4.1.3 on 2022-12-06 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_sillasprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='id',
        ),
        migrations.AlterField(
            model_name='profilefeeditem',
            name='UserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=1, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
