# Generated by Django 4.1.3 on 2022-12-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_remove_profilefeeditem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillasprofile',
            name='silla',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
