# Generated by Django 4.1.3 on 2022-12-06 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_alter_sillasprofile_silla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeeditem',
            name='UserProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
